### ISSUE TITLE
Feature suggestion: Save to a custom directory, and save as Epub.

### ISSUE THREAD

**Issue by nutpantz** [JonasCz/save-for-offline#12] opened 2015-04-28 21:55 UTC
I would love a way to save the downloaded web page to a custom directory.
Would be great if the directory that the pages is saved in is similar to the web page title.
A save as epub option would be a life saver ( its format is based on HTML, and it's an open source format)

Thank you for all your work.

**Comment by JonasCz** [comment] 2015-04-29 10:48
Svimg to a custom directory is coming ! Right now, pages are saved in /sdcard/Android/data/Jonas.tool.saveforoffline/ .

I'll look into epub.

**Comment by JonasCz** [comment] 2015-05-02 20:37
Will probably do this tomorow or the day after.

**Comment by nutpantz** [comment] 2015-05-03 22:38
Fantastic, I will report back with any issues I find.
Thank you for your effort.

**Comment by JonasCz** [comment] 2015-05-04 18:59
I've started on some modifications, it already kind of works, I will do a rewrite in a few days to fix all the other problems which turned up also. Will upload a new release build once i'm done. Nice to see some interest in my project :-)

I'm not sure about epub, I'm quite busy, but if it's not too much work, i'll do it.

**Comment by JonasCz** [comment] 2015-05-06 19:15
This is now implemented, and it seems to work for me. Let me know if something does not work. Also note that the Play Store version is outdated and broken, so you'll have to download the APK from the releases section or compile it yourself. More fixes and improvements coming !

**Comment by nutpantz** [comment] 2015-05-06 21:11
When I tried downloading a page from wikipedia (en.m.wikipedia.org/wiki/Dominoes)
It force closes, but stays in the notification bar  saying it's saving web page.
When i try to cancel it force closes again and force closes again when I try to cancel and stays in notification bar.
I have to forcestop from app info. However it seems to download the webpage just fine but can't finish or close off properly.
but I did get it to download a different page just fine.

I get most of my stuff from fdroid.

**Comment by JonasCz** [comment] 2015-05-07 05:54
Okay, I will fix it.

**Comment by JonasCz** [comment] 2015-05-07 11:44
This should be fixed now. Let me know if it crashes on any other websites. More fixes coming.

**Comment by nutpantz** [comment] 2015-05-07 19:19
Another web page failed, however it still downloaded the text which was the important partforum.xda-developers.com/galaxy-s3/help/luks-manager-mounts-volumes-root-t2662737
I don't mind that it fails from time to time, but it not closing or canceling with out forcing it is a pain
Than you for all your hard work

**Comment by JonasCz** [comment] 2015-05-09 18:12
Fixed now, cancelling should be also fixed now.

**Comment by nutpantz** [comment] 2015-05-10 23:03
Tried downing a few pages, found a few that hung at downloading page, never saw the cancel download option in the status bar notification at all now.
Lost the page links sorry.

**Comment by JonasCz** [comment] 2015-05-11 17:55
Will look into it.

**Comment by JonasCz** [comment] 2015-05-14 17:42
I cannot reproduce this, can you post some links to repro this ? The cancel option should _always_ be there though.

**Comment by nutpantz** [comment] 2015-05-14 18:50
I just installed an ad blocker host file, and since your app is 5x faster and not one site has failed to copy. I'll keep testing and update if I find anything.
But when it's downloading a site there is no cancel in the notification bar. Just saving site

**Comment by JonasCz** [comment] 2016-07-17 12:10
This is now implemented, you can choose where to save the files in the preferences. 

Saving as Epub is probably not possible at the moment.

**Closed as completed by JonasCz** 2016-07-17 12:10 UTC
